# Generated by Django 3.1.1 on 2020-09-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crew',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('des', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='feed',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('des', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='gathering',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('date', models.DateTimeField()),
                ('crew_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.crew')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('crew_ID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='HAE_DB.crew')),
            ],
        ),
        migrations.CreateModel(
            name='gathering_participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gathering_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.gathering')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.user')),
            ],
        ),
        migrations.CreateModel(
            name='gathering_comment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('gathering_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.gathering')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.user')),
            ],
        ),
        migrations.AddField(
            model_name='gathering',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.user'),
        ),
        migrations.CreateModel(
            name='feed_comment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('feed_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.feed')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.user')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.user'),
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField()),
                ('location_X', models.FloatField()),
                ('location_Y', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.user')),
            ],
        ),
        migrations.CreateModel(
            name='crew_header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.crew')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.user')),
            ],
        ),
        migrations.CreateModel(
            name='account',
            fields=[
                ('user_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HAE_DB.user')),
            ],
        ),
    ]
