# Generated by Django 3.1.2 on 2020-10-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAE_DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='yolov5/yolov5/inference/images')),
            ],
        ),
    ]
