# Generated by Django 3.1.2 on 2020-10-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAE_DB', '0002_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='image',
            field=models.ImageField(null=True, upload_to='test'),
        ),
    ]
