# Generated by Django 3.1.2 on 2020-10-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAE_DB', '0004_auto_20201027_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
