# Generated by Django 3.1.2 on 2020-10-27 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAE_DB', '0005_auto_20201027_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crew',
            old_name='image',
            new_name='_image',
        ),
    ]
