# Generated by Django 3.1.2 on 2020-10-27 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAE_DB', '0006_auto_20201027_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crew',
            old_name='_image',
            new_name='image',
        ),
    ]
